config/routes.rb
URLShortener::Application.routes.draw do
  
  resources :urls do
    get 'new', :on => :member
    post 'shorten_url', :on => :member
    post 'check_stats', :on => :member
  end
  
  resources :urls
  
  root :to => 'urls#new'
  
  match 'u/*url' => 'urls#redirect'

end

app/models/url.rb
class Url < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  
  def new
    @url = Url.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @url }
    end
  end
  
  def shorten_url
    #create random string
    chars = [('a'..'z'),('A'..'Z')].map{|i| i.to_a}.flatten
    loop{
      @short_url =(0..6).map{chars[rand(chars.length)]}.join
      @urls = Url.find(:all, :conditions => ["short_url LIKE ?", @short_url])
      break unless (@urls.length)>0
    }
    
    
    
    @url = Url.new(:long_url => params[:long_url], :short_url=> @short_url)
    
    respond_to do |format|
      if @url.save
        format.html { render "show" }
        format.json { render json: @url, status: :created, location: @url }
      else
        format.html { render action: "new" }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
    
  end

  def show
    @url = Url.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @url }
    end
  end
  
  def redirect
    @key = params[:url]
    @url = Url.find(:all, :conditions => ["short_url LIKE ?", @key])
    
    if @url.length ==0
      flash[:notice] = "No link to redirect!"
      redirect_to :action => "new"
    else
      @url[0].redirections = @url[0].redirections + 1
      @url[0].save
      redirect_to @url[0].long_url
    end
  end

  def check_stats
    @key = params[:short_url]
    @temp = @key.partition("/u/");
    @key = @temp[2];
    @url = Url.find(:all, :conditions => ["short_url LIKE ?", @key])
    if @url.length == 1
	 @url = @url[0]
    
   	 respond_to do |format|
     
      	 	 format.html { render "show" }
       	 format.json { render json: @url, status: :created, location: @url }
      
   	 end
    else
	flash[:notice] = "Link doesn't exist in data base"
       redirect_to :action => "new"
    end
	
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>URLShortener</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/check_stats.html.erb
<h1>Urls#check_stats</h1>
<p>Find me in app/views/urls/check_stats.html.erb</p>

app/views/urls/new.html.erb
<h1>URL Shortener</h1>

 <% if @error %>
    <div id="error_explanation">
      <h2> Error </h2>
      <%= @error %>
    </div>
  <% end %> 

<h2> Make your long url short! </h2>
<%= form_tag :controller => "urls", :action => "shorten_url" do %>
  <%= text_field_tag(:long_url) %>
  <%= submit_tag("Shorten me!") %>
<%end%>
<h2> Check stats of your shortened url </h2>
<%= form_tag :controller => "urls", :action => "check_stats" do %>
  <%= text_field_tag(:short_url) %>
  <%= submit_tag("Check stats") %>
<%end%>

app/views/urls/show.html.erb
<p>
  <b>Long url:</b>
  <%= @url.long_url %>
</p>

<p>
  <b>Short url:</b>
  <input type="text" value="<%= 'localhost:3000' + '/u/'+ @url.short_url %>" readonly size="50"/>
</p>

<p>
  <b>Redirections:</b>
  <%= @url.redirections %>
</p>

<%= link_to 'Back', new_url_path %>